### ISSUE TITLE
Enable hyperlink function for Learn More and arrow in the homepage What We Do panels

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#10]
- [x] Enable hyperlink to internal page through the hero carousel Learn More and arrow (make the arrow active too)

Just one example is shown, but none are functional.

The Learn More link and arrow are not taking us anywhere
![Screen Shot 2021-06-14 at 14 46 59](https://user-images.githubusercontent.com/13530245/121943239-62312400-cd1f-11eb-980f-c61a20883510.png)

@rayrshah

**Comment by rayrshah** [comment]
@adambard1 where should each link take you?

**Comment by adambard1** [comment]
The tile headings tell you what page they go to, but we don't know their
priorities. Let's ask Gunika what pages should be highlighted in
the carousel.

**Comment by adambard1** [comment]
The hyperlinks provided in the carousel can link to the internal pages of the same name as the heading

**Comment by kiran-td** [comment]
@rayrshah and @adambard1 hyperlink has been added to banner as well as home page where learn more is available except below title as there is no relevant pages.

Data center Preparation
Network & Unified Communication
Advanced Technologies
Managed Services

**Comment by adambard1** [comment]
Yes, we are waiting for clarification on the content in the tiles. Thanks @kiran-td

**Comment by adam-td** [comment]
Update: the content in the tiles was taken from the existing 3t site (3tsa.com), where there are bookmarks to a paragraph on each. I will see if I can find similar content on our site.

**Comment by adam-td** [comment]
These links have been temporarily assigned by me. Will see what client wants to do.
