### ISSUE TITLE
Content issues on 'Design & Deploy'

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#13]
Hero image in the design should have content in a panel lowerleft
![Screen Shot 2021-06-14 at 18 42 44](https://user-images.githubusercontent.com/13530245/121968427-50ac4400-cd40-11eb-9263-06fae9a1ff62.png)

Our page has this content under the image
![Screen Shot 2021-06-14 at 19 36 28](https://user-images.githubusercontent.com/13530245/121971943-ef886e80-cd47-11eb-9623-1ad318986d09.png)

**Comment by adambard1** [comment]
The content on this page needs designing in, so it is balanced across the page and works with the elements of the page. It does not seem that the page should start with bullet points.
Current copy including bullets:
![Screen Shot 2021-06-14 at 18 26 12](https://user-images.githubusercontent.com/13530245/121969022-6d954700-cd41-11eb-8f72-554842131752.png)


AS above the H2 and following paragraph can fill the hero panel, but if the bullet points that follow are used are used then they should use this element
![Screen Shot 2021-06-14 at 18 49 40](https://user-images.githubusercontent.com/13530245/121968959-4cccf180-cd41-11eb-85e8-a743133dfc30.png)

**Comment by adambard1** [comment]
I have [rewritten the content for the first three bullets here](https://docs.google.com/document/d/1olhUrm0CHNrZUFrNuddJG6_1dNaHdlsw/edit) and they can fill panels as above

**Comment by adambard1** [comment]
@rayrshah @TD-Kyle

**Comment by kiran-td** [comment]
@rayrshah and @adambard1 can you please take a look now https://3t.thinkdesign.com/demo/system-integration/microsoft-gold-partner/design-deploy/

**Comment by adambard1** [comment]
There's no content in the hero section?
![Screen Shot 2021-07-14 at 10 26 37](https://user-images.githubusercontent.com/13530245/125639132-b8f77fc9-4d19-4cb8-97de-037c60766372.png)

**Comment by kiran-td** [comment]
yes hero section content section creation work is running once done we will add those to sub page.

**Comment by adambard1** [comment]
> @rayrshah and @adambard1 can you please take a look now https://3t.thinkdesign.com/demo/system-integration/microsoft-gold-partner/design-deploy/

What am I supposed to be looking for?

**Comment by adambard1** [comment]
The page has several content formatting issues that would be great to address, but I'd need to be able to edit, content, alter the style of content and align heading is sections of the page where they are not formatted correctly or aligned – this type of editing is possible for me through elementor.

**Comment by adambard1** [comment]
I have redesigned the first main content section, but the H2 and content ought to go in the hero as detailed above
![Screen Shot 2021-07-14 at 12 44 09](https://user-images.githubusercontent.com/13530245/125660569-f99367d0-63c2-4416-9bce-5af604787f88.png)

**Comment by adambard1** [comment]
How do we reduce the height of the feature panels @kiran-td ?
![Screen Shot 2021-07-14 at 13 31 49](https://user-images.githubusercontent.com/13530245/125666444-360a6c28-51cf-46c0-a668-4acbf047ef01.png)

**Comment by rayrshah** [comment]
@adambard1 the height issue should be fixed with more content

**Comment by adambard1** [comment]
Looking to make this section
![Screen Shot 2021-07-14 at 14 20 07](https://user-images.githubusercontent.com/13530245/125672649-ac120103-0076-4e58-9e61-6463d4586013.png)

Match proto section
![Screen Shot 2021-07-14 at 14 20 50](https://user-images.githubusercontent.com/13530245/125672718-b9f3f8e3-6c54-4834-9459-621ed1a510cd.png)

except for our list style size (which isn't available/selectable yet)
