### ISSUE TITLE
Add Automation and AI page  to homepage hero carousel

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#18]
The demo has 2 carousel pages whereas the 3t.thinkdesign.com has 5 pages

Let's provide 4 carousel pages as per the approved design (use the first four from 3t.thinkdesign.com)
The client can choose which pages to feature if not these.

**Comment by kiran-td** [comment]
Done on demo one

**Comment by adambard1** [comment]
The client had provided content for 5 pages on the homepage carousel. Please add and Automation and AI page after 'Security'

copy is:
(heading) Automation & AI
(body copy) AI helps us accomplish tasks beyond our human limitations, but with more data, comes the need for accelerated compute and scale-out storage resources.

**Comment by kiran-td** [comment]
@rayrshah and @adambard1 it has been added.
