### ISSUE TITLE
Add Microsoft Gold Partner page copy

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#19]
The 'Microsft' page in the System Integration menu should now be called Microsoft Gole Partner. The copy [is here](https://docs.google.com/document/d/1xlLsiMCqy62_47jwdMKu0X3xQgumvPyd/edit#heading=h.htggz76k7c9a)

**Comment by kiran-td** [comment]
https://3t.thinkdesign.com/demo/system-integration/microsoft-gold-partner/

Do we need to keep 3 submenu underneath this page into navigation?

**Comment by adambard1** [comment]
That is how the client designed it. If there is another option we can
consider it.
