### ISSUE TITLE
Implement the Dell web syndicated content, adjust bottom margin on overview page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#20]
The Dell page on the System Integration menu pulls content from Dell's site, which content will look like this page when implemented https://abc.com.qa/dell-emc/

The client provided the following two pieces of code to accomplish that but no instruction
`<div class='zift_plugin' id='8a9982206ed1b0d6016ed26d3c301cfe'></div>`
`<script type='text/javascript' src='https://widgets.ziftsolutions.com/dell.ziftsolutions.com/js/8a9982206ed1b0d6016ed26d3c301cfe'  charset='utf-8'></script>`

**Comment by adambard1** [comment]
The Dell Technologies showcase would appear under the hero, with a margin to the top of the content matching the margin to the first heading on other pages

**Comment by kiran-td** [comment]
As of now i have implemented the main page. May be need to check with images rights and usage :) . Also in actual reference there is a sub page which is linked to each section. How we want to implement further do let me know. 
https://3t.thinkdesign.com/demo/system-integration/dell-emc/

**Comment by adambard1** [comment]
Hilarious that their first page has a type in the title "Stop an Nothing". Don't know what we're worried about. ![Screen Shot 2021-07-09 at 16 13 07](https://user-images.githubusercontent.com/13530245/125131324-95719380-e0d0-11eb-981f-ba5d0ba6020c.png)

**Comment by adambard1** [comment]
It looks fine btw Kiran – same as their other site's syndicated page.

**Comment by rayrshah** [comment]
- [ ] Put headings bottom - left
- [ ] Make clickable

**Comment by kiran-td** [comment]
@rayrshah 
from subpages  the reference page https://abc.com.qa/dell-emc/

When you click on each box element it does not have same data to it.

For example 

https://abc.com.qa/dell-emc/?zCustomPage=Stop%20At%20Nothing

https://abc.com.qa/dell-emc/?zCustomPage=Optimize%20IT

https://abc.com.qa/dell-emc/?zCustomPage=Mid-Market%20Solutions

So in order to do that we can not do it into same page. Either we need to create a custom post types with one elementor page. where data needs to create. 

Or we can create a separate pages for the subpages

Overall in the same page like reference page it's not possible as in reference site it's hard coded with their backend system. We don't have any functionality with elementor or wordpress which we can do with wordpress standards.

**Comment by adam-td** [comment]
Just confirming we are looking to host the Dell syndicated content on the site, not build new pages for all the content. There should be some way to pull the Dell content (without pulling the header or footer of their page, if it is hosted on a page).

**Comment by kiran-td** [comment]
@adam-td and @rayrshah content syndication has been done to this page :)  Just check the page and let me know if required title or not?

**Comment by kiran-td** [comment]
![image](https://user-images.githubusercontent.com/83412169/128166848-f8a0011c-622e-4ecc-9c6b-5b43e4ccf0da.png)

**Comment by adam-td** [comment]
Great that this is working! We don't want to either the search bar or the "Contact us today" panel on any of the content we host.

Everything else is good. If we can block those, it is done.

![Screen Shot 2021-08-04 at 10 09 23](https://user-images.githubusercontent.com/87426372/128196090-e3561326-a7e4-4c94-b098-a4a9ae6a4323.png)

![Screen Shot 2021-08-04 at 10 10 19](https://user-images.githubusercontent.com/87426372/128196085-ad3f1658-1195-4196-b717-e7170cca6997.png)

- etc. don't show this on any page

**Comment by kiran-td** [comment]
@rayrshah @adam-td this is done

**Comment by adam-td** [comment]
OK, that's great. Please increase the size of the bottom margin from the grey frame for the content to the footer for the overview content for consistency with other pages...
![Screen Shot 2021-08-05 at 14 40 23](https://user-images.githubusercontent.com/87426372/128403979-bbf4f0c8-7a84-4a6d-b2d3-7a73077ecbc1.png)

- other Dell pages seem to create a large enough bottom margin, e.g this content clicking through from Dell Technologies Services

![Screen Shot 2021-08-05 at 14 44 01](https://user-images.githubusercontent.com/87426372/128404167-3f9635bb-39e4-481a-b44e-db2a7149b5dc.png)

**Comment by adam-td** [comment]
I have done this.
