### ISSUE TITLE
Footer UI

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#24]
The first vertical menu of the three on the rhs of the footer (headed System Integration) is a bit lower than the second and third menus.

I believe this section should replicate the Header menu so should have four vertical columns, to mimic the header menu, not the prototype's three vertical columns.

![Screen Shot 2021-07-09 at 17 43 59](https://user-images.githubusercontent.com/13530245/125138768-42520d80-e0dd-11eb-9c4f-9fd379e484ba.png)

**Comment by adambard1** [comment]
Also, the logo should be placed in the footer. Use just the logotype "3T | Total Technical Triangle" and not the triangles that start the logo. The client will come back to us to confirm if we can use the triangles in white.

**Comment by adambard1** [comment]
- [ ] @rayrshah to get text file for logotype in EN and Arabic

**Comment by rayrshah** [comment]
[white-3T.zip](https://github.com/rayrshah/3T/files/6856573/white-3T.zip)

**Comment by adam-td** [comment]
Hi @rayrshah sorry, the footer content is in color #E3E3E3

Also, not sure why but the svg had a large margin around it when uploaded into the icon widget, requiring -125 top and bottom margins to fit?

**Comment by adam-td** [comment]
There is an issue with trying to size the columns in the footer. I can't get the lh column to size to 50%.

Lt's leave out the 'About Us' menu, since there is a small paragraph in the footer about 3T

**Comment by adam-td** [comment]
3T grey logo SVG in the footer needs to be responsive

**Comment by adam-td** [comment]
Footer should be boxed width 1296

**Comment by kiran-td** [comment]
I guess as of now footer width is 1296. I believe that to change the width from elementor could be an issue and for that we are looking into it.

**Comment by adam-td** [comment]
OK.we are not seeing balanced margins on the footer.

![Screen Shot 2021-07-30 at 10 01 00](https://user-images.githubusercontent.com/87426372/127664351-031332ff-e892-4703-8c19-68568d00500c.png)

**Comment by rayrshah** [comment]
@kiran-td see above.

Loose the column for contact. 

Place contact at the level of "All Copyright 2021"  - make sure it's a link, and right align it

**Comment by rayrshah** [comment]
Roughly like this:
![image](https://user-images.githubusercontent.com/2479135/127744626-772bef19-87e1-47e2-86eb-dccd76fe856a.png)

**Comment by adam-td** [comment]
I added a 40px rh margin to the lh column, which looks OK. It is responding to margins now anyway, so we can adjust it if necessary.

Contact us link still to go in to the Copyright footer.

**Comment by adam-td** [comment]
I added the Contact Us button.

Assuming it responds predictably, this is done.

Won't we want a Site by Think Design link in there too?
