### ISSUE TITLE
Logo doesn't appear in Firefox (latest version)

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#28]
Not in Firefox
![Screen Shot 2021-07-09 at 18 28 10](https://user-images.githubusercontent.com/13530245/125141750-e50d8a80-e0e3-11eb-8f56-db1a1499f2a8.png)

But is in Chrome
![Screen Shot 2021-07-09 at 18 27 56](https://user-images.githubusercontent.com/13530245/125141756-e9d23e80-e0e3-11eb-92e5-a603b1d5302a.png)

**Comment by kiran-td** [comment]
@rayrshah @adambard1 it's fixed.
