### ISSUE TITLE
implement template on search page, change left and right margins and address result issues on results page

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/3T#29]
- [x] Make this close to the design
- [ ] use the typography style guide

**Comment by kiran-td** [comment]
Done @rayrshah @adam-td

**Comment by adam-td** [comment]
The margins are too tight here. make the boxed width 1196, please.

Also, there are issues with clicking through the results, e.g. this search for "dell" which is the first thing I tried

<img width="1280" alt="Screen Shot 2021-08-04 at 10 14 56" src="https://user-images.githubusercontent.com/87426372/128197075-77722f90-fa0c-4395-a7cc-bce7ccad8dac.png">

takes me to this

<img width="1277" alt="Screen Shot 2021-08-04 at 10 15 08" src="https://user-images.githubusercontent.com/87426372/128197128-ee382a39-230e-4b56-9fd1-2c95fd2d2861.png">

**Comment by adam-td** [comment]
Other search results than those for "dell" appear to be working well and take you through to a relevant page. It would be great if we could take the user to the word on the page that they searched for instead of just the top of the page, but hold off on that till other issues are done.

**Comment by kiran-td** [comment]
Results Page Left and right margins and boxed width 1196 issue soved.
