### ISSUE TITLE
Add unique Icons for 'What We Do' section of homepage content

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#31]
The [source content document](https://docs.google.com/document/d/1utGxb_q3DISUSIQKuFrRvv_rKMyAxac_/edit) provides logo direction for each panel.
Icons must be copyright free

**Comment by kiran-td** [comment]
@rayrshah and @adambard1 icons has been added

**Comment by adambard1** [comment]
I have done this on /demo which needs pulling to the root site @kiran-td

**Comment by adambard1** [comment]
![Screen Shot 2021-07-16 at 10 37 45](https://user-images.githubusercontent.com/13530245/125965817-e1edac6f-9905-45ba-b3d5-029f915e7e4f.png)

**Comment by adambard1** [comment]
If possible, the logo could be bigger in the circular frame. I cannot find where that is edited.

**Comment by adambard1** [comment]
as mentioned in #46
