### ISSUE TITLE
Prevent Text Editor body copy font changing size when copy editing and enable style selection

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#35]
@kiran-td pls see the attached video.

In elementor when I go to edit some (but not all) content fields with the 18pt body copy text, the moment I click in to edit the font changes size to 16 pt, and I can't revert it no matter what I do. In some cases, the font stays in 16pt even if I do not update and save changes.

Download the following screen recording of attempting to edit copy on the [Design and Deploy](https://3t.thinkdesign.com/demo/system-integration/microsoft-gold-partner/design-deploy/) page
https://user-images.githubusercontent.com/13530245/125625317-87e394d2-5758-4c2c-bc51-a569a7a062ee.mov

If I then look in the Font typography editor, the font has no size. Adding a size does not change anything. Selecting the body Copy style, which has the correct point size produces an incorrect result.

example from another text field on the same page that I clicked into and the font size changed
![Screen Shot 2021-07-14 at 09 04 21](https://user-images.githubusercontent.com/13530245/125626796-45296e4a-6e60-41a6-bcac-76bb505117ad.png)

**Comment by adambard1** [comment]
This issue still applies on the level 2 page left hand side column text editor field (still working in /demo as not all templates are in root)

- Before clicking in the text editor field to edit

![Screen Shot 2021-07-19 at 13 18 20](https://user-images.githubusercontent.com/13530245/126200521-05478eaa-f541-45b5-8974-669ba581cb10.png)

Once clicked in and making an edit (in this case removing the period at the end of the sentence
![Screen Shot 2021-07-19 at 13 20 20](https://user-images.githubusercontent.com/13530245/126200747-cf7fe436-087c-4f53-ae9b-af6946e266a7.png)

**Comment by adambard1** [comment]
The typography selectors, global or local, are not responsive in the Elementor text editor widget
(though the heading widget does respond to style selection)

**Comment by adam-td** [comment]
Not sure about this issue. It seems to still happen in some window, but I will close it as all copy editing is done.
