### ISSUE TITLE
Content not displaying paragraph breaks.

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#37]
In Elementor, I currently have to add double line breaks to get spacing between paragraphs. This is the worst solution since when we add paragraph breaks to the code we will then have to remove the extra line breaks, but I need to create the separation somehow to show the client.

- [ ] enable paragraph breaks to show in the main content window at 150% of the line-height for the particular style (don't implement this for lists)

- Paragraph break showing in Elementor content editor, but not in the content window. This is inconsistent as the first paragraph space is recognized.
![Screen Shot 2021-07-14 at 11 18 55](https://user-images.githubusercontent.com/13530245/125647678-b1f68997-a99a-4a61-986d-27b4a7be30fa.png)

- Additional line break added to create paragraph break in the content, to emulate the source content
![Screen Shot 2021-07-14 at 11 18 45](https://user-images.githubusercontent.com/13530245/125647889-3260319b-4ec1-4444-9a88-86abfb3faa82.png)

I will add in the style guide that all paragraph breaks are 1.5em (150%) of the line-height of the style, so it is a noticeable difference .

**Comment by kiran-td** [comment]
@rayrshah @adambard1 this is done

**Comment by adam-td** [comment]
This appears to be down to some styling that has been paste over in some cases. all styling is to be stripped out of pasted in copy. Copy is to be pasted in plain text only. Do not create headings and paragraphs in the same text window. I will leave. the issue open until we are sure that paragraph breaks are being repsected
