### ISSUE TITLE
Hero copy section revisions to match prototype

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#39]
Currently, the background to the copy is white. Spacing of the copy not quite as prototype
![Screen Shot 2021-07-14 at 18 59 45](https://user-images.githubusercontent.com/13530245/125705919-9dd62f0d-8794-4b48-a07b-4ddcb0723f73.png)

Should be light gray #f6f6f6 and off center spacing (border for content are 60L, 70R)
![Screen Shot 2021-07-14 at 19 36 00](https://user-images.githubusercontent.com/13530245/125705954-acf97c36-aa3e-4968-9333-5b2be5460cb2.png)

**Comment by adam-td** [comment]
I have created a template that seems to match the prototype's margins for the typography section.  It's in /demo and called "Hero plus adaptive content"

**Comment by kiran-td** [comment]
@rayrshah @adambard1 this is done on below page
https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/solution-assessment/

**Comment by adam-td** [comment]
WE have said that the one I created as a template was fine so am using that.
