### ISSUE TITLE
Formatting of page sections not working on root site

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#42]
There are various elements not working or formatting correctly on each page.
e.g.

- Homepage > What we do
![Screen Shot 2021-07-15 at 08 21 03](https://user-images.githubusercontent.com/13530245/125787066-9bd875bb-7d4f-4aad-92dd-22084a811fb1.png)

- Solutions Assessment > Why migrate to Azure
- ![Screen Shot 2021-07-15 at 08 21 51](https://user-images.githubusercontent.com/13530245/125787188-6235537d-27e3-4fba-ad81-99c92a1e5934.png)

- Microsoft Surface page (no images)
![Screen Shot 2021-07-15 at 08 22 48](https://user-images.githubusercontent.com/13530245/125787299-f8aa7935-4d7f-4b4d-8e2a-b57f80e4e0c5.png)

**Comment by kiran-td** [comment]
@adambard1 @rayrshah make a hard refresh once or check in incognito. it was due to old site cache.

**Comment by adambard1** [comment]
OK, thanks, Kiran
