### ISSUE TITLE
logo frame in feature panel should be 112px diameter, it is 80

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#46]
Current site
![Screen Shot 2021-07-16 at 10 47 24](https://user-images.githubusercontent.com/13530245/125966367-e7b4fb95-74e8-4fc9-98b3-3afa39c95767.png)

Prototype
![Screen Shot 2021-07-16 at 10 49 09](https://user-images.githubusercontent.com/13530245/125966480-f167d33a-40b6-40cd-86ce-7265f7b9a50d.png)

**Comment by adambard1** [comment]
as mentioned in #31

**Comment by kiran-td** [comment]
@rayrshah @adambard1  this is done

**Comment by adam-td** [comment]
It is not yet done on Level 1 pages

- proto

![Screen Shot 2021-07-26 at 10 49 10](https://user-images.githubusercontent.com/87426372/127009476-f7229708-aa95-4555-8a52-560eca347a67.png)

- our site (e.g. https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/)
![Screen Shot 2021-07-26 at 10 50 00](https://user-images.githubusercontent.com/87426372/127009635-a6600f4d-0e69-4a1d-a22b-c0f534bde4df.png)

**Comment by adam-td** [comment]
I think this is done
