### ISSUE TITLE
Changing the size/position of a horizontal line in the Level 2 page lhs column

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#48]
A horizontal line matching the length of the heading (or running full width if the heading wraps) appears in any Heading widget that I add to the LHS section, and it is not editable

it shouldn't run full width or be immediately under the Heading, but be an independent 108px wide separator under the Heading.

Could you please explain how to edit it, or remove it, so we can instead add a divider from the Elementor menu that we can size?
![Screen Shot 2021-07-20 at 10 35 07](https://user-images.githubusercontent.com/13530245/126342924-c37baf67-2c02-46f6-b4c4-ca25ea0c4680.png)

- Prototype
![Screen Shot 2021-07-20 at 10 31 54](https://user-images.githubusercontent.com/13530245/126342382-f20fa4a0-8cbf-448b-aa98-135e4d290b9d.png)

**Comment by adam-td** [comment]
I was thinking that this line is static css, is it something else @kiran-td? The issue about stripping all of that out has been closed.
