### ISSUE TITLE
 Move everything done to date from /demo to root (again)?

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#49]
Hi, @kiran-td 
I lost the header and the footer by updating their boxed width as per the prototype, creating a template, and then deleting the template one which didn't have a fixed width!! I didn't know that this would delete the headers and footers site-wide.

I have still been working on /demo. I couldn’t find the templates or images from /demo in root, so I carried on building in /demo.

I have completed page edits for:

1. Homepage
2. About Us
3. Dell EMC
4. Microsoft Gold Partner
5. Solutions Assessment
6. Design and Deploy
7. Support and Management

Can you please move them to root and bring the templates (page, section, and global), colors, and typography styles and images from /demo to root also?

I will carry on editing the rest of the pages in root when the templates are there, but until everything is there I will build in /demo

In site settings theme style I created typography for body copy, which corrected the spacing for most text edit boxes, so that should come over too.

If it’s easier we can just carry on working in /demo and pull the whole things to root when we are done, but I know @rayrshah  wanted everything in root for the client to check periodically.

**Comment by kiran-td** [comment]
@adam-td @rayrshah first of all we need to define where we have to work. So what i want to do today is to merge the changes. As when we moved to roor design level changes by designer done in root level. Right now content is update by adam is in demo. So if i make import export using all in one there is chance to loose the changes.

So first of all i want my designer to manully replace the change to demo and than we make import demo site to the root level. As we are using pro functionality so separate header and footer functionality comes up with pro. Right now demo has not activated licence.  So right now when we go for change into header it's ask for reactivate licence for the site. 

So what i suggest that @adam-td if you are doing any content changes please do it in demo one. Meanwhile my team will replace global settings and header issue to be fixed. and we will move it late night or early morning. After i will inform you so then we need to do everything in root afterwards.

**Comment by adambard1** [comment]
Thanks, Kiran. Actually, I think that to be able continue to work in /demo
is possibly good until publishing the whole site, unless it causes cost
implications. If we just had one address I fear that some error could
affect everything, so I prefer having a safe place to work as Elementor
does not appear to supply warnings for unexpected actions that have a
global affect.

**Comment by kiran-td** [comment]
@rayrshah @adambard1  site has been moved to demo now whatever you do changes make it on root.
