### ISSUE TITLE
Create responsive image for Microsoft Support main content

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#50]
I made an image of Microsoft services (from their support page) for the Microsoft Support and Management page. It needs to be built from individual tiles to be responsive. The icons attached are very tiny, so if you can find svgs that'd be great, @kiran-td 

![Microsoft products](https://user-images.githubusercontent.com/87426372/126524876-9f085386-b824-426d-a95d-3e4613a14286.png)
![microsoft-edge 64x64x32](https://user-images.githubusercontent.com/87426372/126524879-ecf13d31-24e8-489d-9e94-e31c0a6d4cf0.png)
![office 64x64x32](https://user-images.githubusercontent.com/87426372/126524884-43768be6-2285-4050-a665-d15687a0f444.png)
![onedrive 64x64x32](https://user-images.githubusercontent.com/87426372/126524885-e20b097d-6415-4dd9-9453-43f7aeb72312.png)
![outlook 64x64x32](https://user-images.githubusercontent.com/87426372/126524889-16f77643-6358-4c12-be3d-69ef4bb07055.png)
![shoppingcart 64x64x32](https://user-images.githubusercontent.com/87426372/126524891-ff883a43-7f49-44e3-aec5-ca51b8374d8f.png)
![surface 64x64](https://user-images.githubusercontent.com/87426372/126524894-cf310df1-335a-4f79-bac4-6bbb66d8d9fe.png)
![teams 64x64x32](https://user-images.githubusercontent.com/87426372/126524896-714cc167-51e8-43c4-8d0d-b63dd6d75765.png)
![windows 64x64x32](https://user-images.githubusercontent.com/87426372/126524898-b9eda071-3da4-4302-9990-923c8f3fba71.png)
![xbox 64x64x32](https://user-images.githubusercontent.com/87426372/126524899-3bd04b29-eda1-4149-82ef-8798a1d06971.png)
![microsoft365 64x64](https://user-images.githubusercontent.com/87426372/126525637-71f4c3b4-da8b-4983-a9b1-780618a70c11.png)

**Comment by kiran-td** [comment]
@rayrshah @adambard1  this is done
