### ISSUE TITLE
Sections appearing correctly in Elementor edit screen but not formatting properly when published

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#51]
in /demo e.g. this section on the VMware page

- in the edit window
![Screen Shot 2021-07-21 at 17 45 15](https://user-images.githubusercontent.com/87426372/126564416-8b53736d-d1ac-4217-a1a8-d55e556be329.png)

- When viewing the page
![Screen Shot 2021-07-21 at 17 47 36](https://user-images.githubusercontent.com/87426372/126564545-dc5627ba-cbda-4399-9678-a8ce64c42774.png)

**Comment by adam-td** [comment]
And pretty much the entire https://3t.thinkdesign.com/demo/system-integration/microsoft-gold-partner/support-and-management/
which is fine in the edit window but a real mess published

**Comment by kiran-td** [comment]
@rayrshah @adambard1 currently it's look good please check it on private window.
![Screenshot_8](https://user-images.githubusercontent.com/83412169/126875588-15fe67cf-8353-4484-9ac7-a8f20bd866b2.jpg)
