### ISSUE TITLE
Breakpoints to maintain left and right side margins to main content between 1439 and mobile window sizes

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#54]
Middle part of design for tablet view or small laptop there should be a media query to maintain margins of main content  between mobile and above 1440

**Comment by kiran-td** [comment]
it has been done with the other resolutions as well. Kindly check and let me know

**Comment by adam-td** [comment]
Like other issues today, I am not seeing this as fixed e.g. these screenshots at 1280 (Retina 13" macbook pro) – very tight margins.

<img width="1280" alt="Screen Shot 2021-07-30 at 10 16 10 (2)" src="https://user-images.githubusercontent.com/87426372/127666564-01429c14-72ef-4e05-95f9-297ad39eb37f.png">

<img width="1280" alt="Screen Shot 2021-07-30 at 10 15 44" src="https://user-images.githubusercontent.com/87426372/127666584-40f7344a-ec58-4b34-a4c6-236bbe0930ba.png">

**Comment by adam-td** [comment]
As the window gets narrower, the margins are not being maintained. This is still outstanding.

**Comment by adam-td** [comment]
At and above 1440 ycan see that there are decent sized margins either side of the content (this is the Support and Management page)
![Screen Shot 2021-08-04 at 10 41 13](https://user-images.githubusercontent.com/87426372/128201161-96dcca14-accf-4896-a126-ee57fb3853f7.png)

- but as the width decreases, the left and right page margins are eroded. The inner content does not start to respond until the width is less than the boxed width of the specific section.

<img width="1280" alt="Screen Shot 2021-08-04 at 10 40 39" src="https://user-images.githubusercontent.com/87426372/128201616-9abebec9-b217-44d1-bb06-bc35a107a7ee.png">

The left and right page margins should be maintained (proportionally, anyway) so that content doesn't sit right at the edge of the screen, but also narrows as the screen size decreases.

**Comment by adam-td** [comment]
It's most clear on pages with the 1296 boxed width, like the other vendors' page, where the side margins have disappeared at the smaller screen size.

- **1440**

![Screen Shot 2021-08-04 at 10 51 52](https://user-images.githubusercontent.com/87426372/128203293-445fb1f0-2480-4ae7-8a70-fcf5dae99580.png)

- **1280**
<img width="1280" alt="Screen Shot 2021-08-04 at 10 54 09" src="https://user-images.githubusercontent.com/87426372/128203469-c1241c56-c4a4-4d28-8499-3a0269d6d6b6.png">

**Comment by kiran-td** [comment]
@adam-td can you check https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/  this page? and let me know your feedback for all the. we have done the required changes for mobile and other resolutions. if it seems fine we can start for other pages.

**Comment by adam-td** [comment]
It looks good at 1280, but the margins are again too tight as you decrease from that and are almost gone by the time you get to iPad in landscape and iPad pro on portrait (both have a width of 1024), and mobile (iPhone x shown below (375x812))

**iPad** margins are too tight
![Screen Shot 2021-08-05 at 14 16 50](https://user-images.githubusercontent.com/87426372/128400954-e46f6c6c-4307-450c-baa7-d64d95c78b8c.png)

**iPhone x** margins are too tight
![Screen Shot 2021-08-05 at 14 23 46](https://user-images.githubusercontent.com/87426372/128402044-5867db69-65ec-4165-a4da-7a81e42c06bc.png)

**iPad pro, portrait** margins are too tight
![Screen Shot 2021-08-05 at 14 24 04](https://user-images.githubusercontent.com/87426372/128401923-689540f7-322a-471b-a619-d1e32f54f64a.png)

- **See what a difference there is when the ipad pro is in landscape mode, where the content has much more room to breathe..**.

![Screen Shot 2021-08-05 at 14 26 30](https://user-images.githubusercontent.com/87426372/128402142-ea0bb7b9-c9a6-4444-bc51-b63461a2a48f.png)

![Screen Shot 2021-08-05 at 14 32 55](https://user-images.githubusercontent.com/87426372/128402805-990cfdbb-1e1c-4eac-bfb6-fef00a432946.png)

As said in the call, we wanted decent space on either side at the mobile level. I think we suggested 2 rem, or so, but looking at the page that's been done, 25px, **say 1.5 rem/24px looks good as a minimum side margin for all mobile conten**t and increase that margin as the window size increases. Aesthetically, it makes sense to me to imagine the left and right border of the information panels as our maximum width for all other content at mobile size.

**iPhone X – lets use 1.5rem as minimum side margins / the panel width as max width for all other content**
![Screen Shot 2021-08-05 at 14 30 01](https://user-images.githubusercontent.com/87426372/128402452-dcf9abf6-c82a-4099-8521-55f03787c989.png)

**Comment by kiran-td** [comment]
Now For Mobile And i-pad both side margins 2rem.

**Comment by adam-td** [comment]
Thanks Couple of comments...
1. OK. looks much better. I had suggested 1.5rem in the comment directly above, but 2 is looking good.
2. The margin hasn't been applied to the text container in the header.

There is an issue with the logo above the boxes but I will open that as a new issue.
