### ISSUE TITLE
Left hand margin for Homepage hero content window should be 4rem

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#55]
Currently, there is no option to set a margin in the Hero slides for the content window. The prototype defines a margin of 58px, but we will use 4rem (64px)

![Screen Shot 2021-07-26 at 09 36 47](https://user-images.githubusercontent.com/87426372/126997997-b01c3297-0c4c-4b21-a373-8ee1815a5f85.png)

**Comment by kiran-td** [comment]
@rayrshah @adambard1 this is done

**Comment by adam-td** [comment]
- I am not seeing this as done. I have cleared my browser cache and looked on incognito.

![Screen Shot 2021-07-30 at 09 51 26](https://user-images.githubusercontent.com/87426372/127663094-07031f0e-f07a-45d2-a35b-0a4e01368532.png)

- This is the measurement of the current margin

![Screen Shot 2021-07-30 at 09 48 10](https://user-images.githubusercontent.com/87426372/127663086-5a0ad63e-ed3c-439c-b238-848b806fe703.png)
