### ISSUE TITLE
Strip out static css but maintain styling

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#56]
This is so each element is controllable through the elementor widget styling and margins and padding are predictable and editable
e.g. the line under the lh column heading2 on Level 2 as in #48

**Comment by adam-td** [comment]
The main issue this appears to be causing is additional but hidden margins in various places, mostly underneath elements

**Comment by adam-td** [comment]
Hi @kiran-td how are we doing on this (and related issue #58

**Comment by kiran-td** [comment]
@adam-td as of now there is no static css which is overwrite elementor.

**Comment by adam-td** [comment]
OK, thanks.

**Comment by adam-td** [comment]
I can't tell if this is done or not, really. Not all Elementor widgets or text boxes repoond predictably, despite the css being stripped out, so I will close on your word that it is all gone.
