### ISSUE TITLE
Device as a Service page is missing from the menu/site

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#57]
The Device as a Service page should be in the Services section, between Workplace Digital Transformation and Security on the dropdown menu. 

It is on the [content brief tab](https://docs.google.com/spreadsheets/d/1ALivAUU5zwuA952XstYhllcrk9FMhY68/edit#gid=1326333945) in the workbook, with all the others. Not sure why it was overlooked?

The content has already been uploaded but put in the 3TSA Service Capabilities page. I have edited it there. You can duplicate it as the Device as a Service page.

**Comment by kiran-td** [comment]
@adam-td you mean to say need to duplicate 3tsa service .. page with the same details?

**Comment by adam-td** [comment]
Use the content from the 3TSA Services page and create a page called Device as a Service. yes.

**Comment by adam-td** [comment]
Are we able to do this @kiran-td – is the issue clear?

**Comment by kiran-td** [comment]
@adam-td yes that is clear and will done soon today.

**Comment by kiran-td** [comment]
This Issue Done

**Comment by adam-td** [comment]
I have moved it to the position proposed by the client in the workbook and added the page to the footer menu
