### ISSUE TITLE
Link setting for padding of sections responding unpredictably

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#58]
In the Edit Section>Advanced tab, clicking the link icon on the padding section without making any adjustment to the settings creates a change in the display of the section. Is this because there is some hidden padding that is 'static css

- e.g. before clicking the link icon to unlink padding. No padding is shown in the settings.

![Screen Shot 2021-07-28 at 09 47 11](https://user-images.githubusercontent.com/87426372/127333699-0892ad6b-ab2e-4b4f-b452-977d7723abb5.png)

- after unlinking, but not making any change to the settings

![Screen Shot 2021-07-28 at 09 51 21](https://user-images.githubusercontent.com/87426372/127334576-c759db56-4641-4e2a-a6de-d2f7f1de031e.png)

**Comment by adam-td** [comment]
![Screen Shot 2021-07-28 at 09 56 00](https://user-images.githubusercontent.com/87426372/127334951-ef59c68f-4a1e-4c3d-9189-cae179124910.png)

**Comment by kiran-td** [comment]
@adam-td It seems we have to do with this way as of now there is no static padding or margin applied from anywhere.  However we can define the gaps between column in elementor layout section

**Comment by adam-td** [comment]
A workaround for this is to unlink the padding on any section where the margins/padding looks off and has no figures in it.
