### ISSUE TITLE
Other Vendor info panes copy not aligned, panes not the same size.

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#60]
Loading svgs into the icon widget, or pngs into the image widget shows them in place but will only show a previously uploaded svg (kemp) on the page, even though I have deleted the kemp image from the media library,

e.g.

![Screen Shot 2021-07-30 at 18 24 15](https://user-images.githubusercontent.com/87426372/127717406-7aa4b080-0e11-4213-9cef-0e76e064a8ec.png)

or

![Screen Shot 2021-07-30 at 18 24 59](https://user-images.githubusercontent.com/87426372/127717442-d283a248-876b-4844-b294-0039f2960d7d.png)

**Comment by adam-td** [comment]
After uploading a new cisco svg, now they're all showing that, though again the icon edit window shows the uploaded correct image.
![Screen Shot 2021-07-30 at 19 05 30](https://user-images.githubusercontent.com/87426372/127719698-6271f981-8465-4ec4-bd27-51d2a42e1330.png)
![Screen Shot 2021-07-30 at 19 05 58](https://user-images.githubusercontent.com/87426372/127719728-d280faba-9f7c-4054-8dfd-c70600236abf.png)
![Screen Shot 2021-07-30 at 19 05 48](https://user-images.githubusercontent.com/87426372/127719731-53ec7366-f694-4784-b187-654ed7d1bf10.png)

**Comment by adam-td** [comment]
so full page, which is completed now with all the right logos and content, is doing this...
![Screenshot 2021-07-30 at 19-06-49 Other Vendors – Total Technical Triangle](https://user-images.githubusercontent.com/87426372/127719854-1936e9d9-e571-434e-9536-e1d9d5c710d4.png)

**Comment by kiran-td** [comment]
@adam-td @rayrshah new svg are uploaded and page looks fine.

**Comment by adam-td** [comment]
great

**Comment by adam-td** [comment]
When I created the page the copy in the right-hand panel of each company info pane aligned with the other info pane in the row and all panels were the same size. See the image above. Now panel sizes aren't necessarily the same as the ones in their row, and the text in the right-hand panel of each box is at a different height. The only row that seems to be unchanged is the Poly/Pulses AI row. Please revert the design so all the headings top align and the info panes are the same size, as per the image above @kiran-td 

We know this client is extremely picky about horizontal alignment of copy.

**Comment by rayrshah** [comment]
- [ ] at 1280px
- [ ] make single column

**Comment by kiran-td** [comment]
Other Vendor Now Single Column From 1280px.

**Comment by adam-td** [comment]
The work has been done but the UI is not balanced, with a very large amount of spacing around the logos and very shallow left and right margins. The panel should be smaller when it moves to one cloumn. I will open another issue about this and about the panel in tow columns which also has unbalanced UI.
