### ISSUE TITLE
Level 1 feature panel icons to be top-centered on their panels 

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#61]
Different from the home page, the Level 1 panel icons should be top-centered on the top line of the panel. On [Microsoft Gold Partner](https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/), they are off-center.

![Screen Shot 2021-08-03 at 09 29 54](https://user-images.githubusercontent.com/87426372/128024084-99641118-0800-4287-8fd4-f955d545e16f.png)

**Comment by adam-td** [comment]
On other pages, e.g. here on [VMWare](https://3t.thinkdesign.com/system-integration/vmware/) where there are 3 panels, they are correctly centered.

![Screen Shot 2021-08-03 at 09 33 15](https://user-images.githubusercontent.com/87426372/128024447-51018826-4b79-438d-ae93-9d8883f8e05f.png)

**Comment by kiran-td** [comment]
@rayrshah @adam-td this is done.
