### ISSUE TITLE
In mobile, feature panel icon position is not top centered.

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#65]
Top icon on feature panels is currently closer to the right than the left.

![Screen Shot 2021-08-09 at 08 46 55](https://user-images.githubusercontent.com/87426372/128709851-df7559a6-adb3-46cd-9a5a-ce65b85dad59.png)

![Screen Shot 2021-08-09 at 08 51 42](https://user-images.githubusercontent.com/87426372/128709842-9c4bfa1a-ba54-4cb1-89a4-e2fc38bea3a0.png)

**Comment by kiran-td** [comment]
Done

**Comment by adam-td** [comment]
It is done on mobile @kiran-td thank you but we need to make sure that we are not affecting things elsewhere on the site.

I have QA'd pages a number of times and I am today seeing issues with the icon centering on pages where there was no issue before, and changes in the heading top alignment where there was no issue before – Micrsoft Security Assessment desktop page now has these issues.
- heading top alignment has changed
![Screen Shot 2021-08-10 at 09 43 21](https://user-images.githubusercontent.com/87426372/128877840-b15130f5-8065-4644-af27-f4e45da3eb28.png)

-icon centering on feature panel now not centered
![Screen Shot 2021-08-10 at 09 44 09](https://user-images.githubusercontent.com/87426372/128877957-2cc32119-1ab7-4517-a97f-154edd011a94.png)

Please HOLD on mobile rollout until we can be sure that rolling out mobile or fixing issues for mobile is not somehow affecting other pages on the site and affecting desktop. – How do we check for this before rolling something out – it does not seem that it makes sense to have to check every page for consistency when a fix is made somewhere else?

**Comment by adam-td** [comment]
Caveat is, @kiran-td if you are sure that work on changing the icon centering on mobile has no chance of affecting the desktop, then maybe it's another issue – and should be an issue on it's own – about the icon position for feature panels needing attention wherever there are 2 panels and not 3 panels in a row?

**Comment by adam-td** [comment]
lifting this issue up @niravpateldev in absence of @kiran-td

**Comment by adam-td** [comment]
> Done

This is not yet done

**Comment by adam-td** [comment]
This issue has been overriden by issue #68
