### ISSUE TITLE
Desktop: Top center icons for Level 2 page feature panels on Security page.

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#66]
These icons, on the Security page, are not top centered.
![Screen Shot 2021-08-10 at 09 33 34](https://user-images.githubusercontent.com/87426372/128894590-b3b8960a-7031-40d5-9610-90a9bc721145.png)

**Comment by kiran-td** [comment]
Done

**Comment by rayrshah** [comment]
@adam-td I think this is  done
