### ISSUE TITLE
Mobile: Feature panels with icons become gray boxes

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/3T#68]

**Comment by adam-td** [comment]
This issue overrides issue #65 (which I have closed). It is based on the appearance of the homepage on mobile in Developer. For the homepage it is connected to issue #72, which needs addressing, though no other page has feature panels with a learn more hyperlink

Current homepage appearance on mobile.
![Screenshot 2021-08-16 at 11-12-31 Total Technical Triangle](https://user-images.githubusercontent.com/87426372/129587047-a005c9bd-d2fb-4fb2-8be8-be7b3ef2ee9b.png)

**Comment by niravpateldev** [comment]
Done
