### ISSUE TITLE
Mobile: Homepage hero slides content text not visible

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#71]
The Hero content on the slides is not visible in mobile
![Screen Shot 2021-08-16 at 10 39 07](https://user-images.githubusercontent.com/87426372/129583188-8afff2b1-e62c-46a7-9d8d-1042eec345e8.png)

**Comment by niravpateldev** [comment]
in Design Slider Content not visible so that why we hide that text.

**Comment by adam-td** [comment]
OK. I understand. However, I will open up a new issue so that you can match the prototype size for the hero image. Let's not apply the slides to the hero. I will add that in that issue.
