### ISSUE TITLE
Mobile: Make Homepage Learn More hyperlinks appear in the same position in each panel

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#72]
In the center section, the Learn More hyperlink appears at various distances away from the content. The learn more should appear at the same position for each panel.

The padding (or margin) below the Learn More hyperlink should mirror the padding or margin above the heading in the panel. 

Current screenshot.
![Screenshot 2021-08-16 at 10-47-30 Total Technical Triangle](https://user-images.githubusercontent.com/87426372/129583634-01e1eff9-5a49-480d-b804-c26c969a7ce7.png)

**Comment by adam-td** [comment]
related to #68

**Comment by niravpateldev** [comment]
this issue done and also 68 no issue Done

**Comment by adam-td** [comment]
> The learn more should appear at the same position for each panel.

This is done



> The padding (or margin) below the Learn More hyperlink should mirror the padding or margin above the heading in the panel.

This is not done. The padding underneath the Learn More hyperlink does not mirror the padding above the heading of the panels – see below. I am not understanding why you are saying it is done @niravpateldev ?

- [ ] Let's set the top and bottom padding (or margin if you are using margins) at 2.5 rem.

![Group 117](https://user-images.githubusercontent.com/87426372/129803613-afe8a242-0e3a-4bbb-8be0-7231ff585c6c.png)

**Comment by niravpateldev** [comment]
Done This Issue
