### ISSUE TITLE
Mobile: Solutions assessment and other pages, remove gray top padding for ROI widget

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#76]
- [x] Remove this top padding circled 1. Page shown is [Solutions Assessment](https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/solution-assessment/) but apply fix to appearance of this widget on all pages

![Screen Shot 2021-08-18 at 14 57 46](https://user-images.githubusercontent.com/87426372/129956403-2d467c08-5fc4-4654-9b66-07622947f333.png)

**Comment by niravpateldev** [comment]
can you plz check first Solution Assessment page first if its ok than we will move this changes all over site.

**Comment by adam-td** [comment]
Yes, this is looking very good.

**Comment by adam-td** [comment]
Looking very good, please roll out!
