### ISSUE TITLE
Mobile: 50px top and bottom pad for ROI widget content

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#77]
- [x] 50px top padding for the ROI content, for the area circled 2

Page shown is [Solutions Assessment](https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/solution-assessment/), but apply wherever there is an ROI panel on the site.

- This applies to the content in the gray section of the widget, under the green heading.

![Screen Shot 2021-08-18 at 15 04 29](https://user-images.githubusercontent.com/87426372/129957020-2a42191d-586c-4988-9bc5-d83f22d126e3.png)

**Comment by adam-td** [comment]
- [ ] 50px bottom padding for ROI widget in mobile for the area circled 3

![Screen Shot 2021-08-18 at 15 16 11](https://user-images.githubusercontent.com/87426372/129958546-85c54810-33b1-408d-b0a7-f2b1fca36b8b.png)

**Comment by niravpateldev** [comment]
can you plz check first Solution Assessment page first if its ok than we will move this changes all over site.

**Comment by adam-td** [comment]
Looks good @niravpateldev let's roll out sitewide
