### ISSUE TITLE
Mobile only: 50px padding under internal section heading, above feature panels

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#78]
- [x] 50px top padding above heading circled 4. NOTE: this is not sitewide, top padding above a heading depends if this is an internal section (content is closely related to section above) or a new section, content not closely related.
- [x] and 50px bottom padding under heading, above feature panels, circled 5

- Page shown is [Solutions assessment](https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/solution-assessment/), only roll out sitewide on mobile where you are clear that content is an internal section
- See [Figma file "Internal section break"](https://www.figma.com/file/oH0sJGfswfMBtm4aenKOl4/Midis-UI-changes-%E2%80%93-Client-only?node-id=2021%3A158) for more info.

![Screen Shot 2021-08-18 at 15 12 49](https://user-images.githubusercontent.com/87426372/129958064-dac621c4-079c-420a-8802-71f1c9e24778.png)

**Comment by niravpateldev** [comment]
can you plz check first Solution Assessment page first if its ok than we will move this changes all over site.

**Comment by adam-td** [comment]
Looking good! please roll out – though if you are unsure about which is a
new section (new content not directly relate to the above content) and
which is an internal section (i.e. closely related to the content above)
ping me.
