### ISSUE TITLE
Mobile: Apply 75px top and bottom pad for new content sections

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#79]
Example shown is [Solutions Assessment](https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/solution-assessment/) page.
This fix applies to New sections of content [See Figma file for further details](https://www.figma.com/file/oH0sJGfswfMBtm4aenKOl4/Midis-UI-changes-%E2%80%93-Client-only?node-id=2021%3A158)

- [x] 75 px top padding above the heading, circled 6.

![Screen Shot 2021-08-18 at 15 35 51](https://user-images.githubusercontent.com/87426372/129961015-b52a44bd-1581-4c01-ba3b-d03738c9db7c.png)

**Comment by adam-td** [comment]
- [ ] 75 bottom pad, area circled 7 (light green)
![Screen Shot 2021-08-18 at 15 37 21](https://user-images.githubusercontent.com/87426372/129961223-a389ea6f-41fc-418f-91ba-67ee5489f345.png)

**Comment by adam-td** [comment]
- [ ] 75 top pad area circled 8
![Screen Shot 2021-08-18 at 15 38 30](https://user-images.githubusercontent.com/87426372/129961396-83365afa-08ce-42d4-b5cd-9e401c760f37.png)

**Comment by adam-td** [comment]
- [ ] 75 px bottom pad (above footer) circled 8
![Screen Shot 2021-08-18 at 15 40 12](https://user-images.githubusercontent.com/87426372/129961613-69fe71e4-64b4-4235-b4e9-b47e77d758b7.png)

**Comment by niravpateldev** [comment]
can you plz check first Solution Assessment page first if its ok than we will move this changes all over site.

**Comment by adam-td** [comment]
Yes, that looks really good! Pls. roll out.
