### ISSUE TITLE
Add 3T logo

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#8]
- [x] add 3T 'three triangle' logo to the header

Jenn designed it like this
![Screen Shot 2021-06-14 at 14 38 33](https://user-images.githubusercontent.com/13530245/121942214-3cefe600-cd1e-11eb-9094-7c5506409560.png)

Do we have an svg file for their logo @rayrshah? This is how it appears on their current site
![3T logo](https://user-images.githubusercontent.com/13530245/121942000-f9957780-cd1d-11eb-968c-c20111486d3a.png)

**Comment by rayrshah** [comment]
Let's make sure what it is first

**Comment by rayrshah** [comment]
here is an SVG of the logo
[3T-total-technical-triangle.svg.zip](https://github.com/rayrshah/3T/files/6664971/3T-total-technical-triangle.svg.zip)

**Comment by adambard1** [comment]
@kiran-td this is still outstanding, there is no 3T logo in the header. [See the prototype for placement](https://www.figma.com/file/DbbtHeEy6aW3fKxVk753m9/3T-Designs?node-id=121%3A1851)
