### ISSUE TITLE
Fix Server Error (500 error) trying to update Other Vendors page

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#84]
Trying to save this page https://3t.thinkdesign.com/wp-admin/post.php?post=3658&action=elementor# getting that 500 error.

Was also working on home page, that one updates fine.

**Comment by adam-td** [comment]
I believe this is a page that was built by nirav? The fonts are wrong, and I am trying to update them.

**Comment by niravpateldev** [comment]
Plz Check This Point, Now i can Save this page.
https://3t.thinkdesign.com/demo2/system-integration/other-vendor/

**Comment by adam-td** [comment]
The page has already been pushed to the live site
