### ISSUE TITLE
Make break point for ROI widget on Solution Assessment page 1152

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#86]
There is overlap of the ROI widget internal heading and copy at the current break point (1024). Raising it to 1152 will prevent this overlap

Overlap at 1025 w
![Screen Shot 2021-09-07 at 11 43 05](https://user-images.githubusercontent.com/87426372/132373560-5d124a0d-6d66-4199-b372-926e7eccb911.png)

**Comment by niravpateldev** [comment]
Plz check This point @adam-td  This is the page url https://3t.thinkdesign.com/demo2/system-integration/microsoft-gold-partner/solution-assessment/

**Comment by adam-td** [comment]
The ROI content needs left and right margins to match the heading margin. There are other issues with the alignment of the content as described in the annotated screenshot below.

<img width="960" alt="Screen Shot 2021-09-29 at 10 10 10" src="https://user-images.githubusercontent.com/87426372/135286828-2acc644b-28f2-4d28-a036-3846af6f26d4.png">

**Comment by niravpateldev** [comment]
Hello @adam-td can you plz check this issue on this url https://3t.thinkdesign.com/demo2/system-integration/microsoft-gold-partner/solution-assessment/

**Comment by adam-td** [comment]
looks good @niravpateldev
