### ISSUE TITLE
Add arrows to enable click to move between homepage hero carousel pages

### ISSUE THREAD

**Issue by adambard1** [rayrshah/3T#9]
- [x] Enable click or swipe to move left or right for the homepage hero carousel
- I think we can do this without adding arrows at either extremity since it is such a well-known interaction.

@rayrshah @kiranvadaria

**Comment by kiran-td** [comment]
@rayrshah and @adambard1 right now it's set on click swipe in desktop and mobile. Do you want me to add and arrows to it?

**Comment by rayrshah** [comment]
@kiranvadaria yes

**Comment by kiran-td** [comment]
@rayrshah @adambard1 this is done
