### ISSUE TITLE
Fix layout bugs on Support and Management page

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#90]
Huge gaps have appeared in the middle of the text box on the [Support and Management](https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/support-and-management/) page, plus numerous spacing problems throughout the page where there are larger spaces than the margins chosen underneath txt boxes.

css now appears in multiple text boxes lower down the page. This css was not previously visible.

Heading sizes have changed and are no longer uniform in the text columns.

**Comment by adam-td** [comment]
Some text boxes' spacing changes when you click in and out of them...

https://user-images.githubusercontent.com/87426372/133510131-3f3a1543-c6a2-42ca-8935-6a8ecced739b.mov

**Comment by niravpateldev** [comment]
Plz check This line height and spacing issue on this Url https://3t.thinkdesign.com/demo2/system-integration/microsoft-gold-partner/support-and-management/

**Comment by adam-td** [comment]
I can't check it on a url that I can't open elementor on. The issue happens in elementor.

I am closing this issue anyway cos it doesn't happen on the main site anymore.
