### ISSUE TITLE
Back Up current site before pushing any changes

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#92]
By EOD I will have completed a round of font changes across the site – except for the broken page in #90 

We need a backup of the site just in case any issues occur, so we don't have to re-do those changes.

Caveat: The Solution Assessment page that is currently most affected by issues may be in good shape on an existing backup. Having that single page available from an existing backup could be helpful if the current issue with the page cannot be fixed quickly.

**Comment by adam-td** [comment]
Please back up when you read this @kiran-td @niravpateldev as I have completed a pass of the whole site for typography and spacing.

**Comment by kiran-td** [comment]
@rayrshah @adam-td latest backup has been completed today.

**Comment by adam-td** [comment]
Great, thanks.
