### ISSUE TITLE
Replace broken page and section from Sep 17 backup as below

### ISSUE THREAD

**Issue by adam-td** [rayrshah/3T#94]
- [x] Replace [Solution Assessment](https://3t.thinkdesign.com/system-integration/microsoft-gold-partner/solution-assessment/) page on current site with Solution Assessment page [from Sep 17 backup](https://3t.thinkdesign.com/demo3/system-integration/microsoft-gold-partner/solution-assessment/)
- [x] Replace Enhance your Industry section on [Workplace Digital Transfromation page](https://3t.thinkdesign.com/services/workplace-digital-transformation/) on current site with the Enhance your Industry section [from the Sep 17 backup](https://3t.thinkdesign.com/demo3/services/workplace-digital-transformation/) – the rest of the page is good and does not need replacing.

**Comment by niravpateldev** [comment]
Done

**Comment by adam-td** [comment]
Thanks, @niravpateldev. I have now reformatted the pages so we have the whole site formatted correctly. Please back up the site asap @kiran-td
